# Generated by Django 4.2 on 2023-05-01 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_light_temphumid_date_created_plantstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilMoisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.IntegerField(default=0)),
                ('moisture', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='plantstatus',
            name='moisture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensor.soilmoisture'),
        ),
    ]
