# Generated by Django 4.2 on 2023-05-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_soilmoisture_plantstatus_moisture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantstatus',
            name='lux',
        ),
        migrations.RemoveField(
            model_name='plantstatus',
            name='moisture',
        ),
        migrations.RemoveField(
            model_name='plantstatus',
            name='surrounding',
        ),
        migrations.AddField(
            model_name='plantstatus',
            name='lux',
            field=models.ManyToManyField(to='sensor.light'),
        ),
        migrations.AddField(
            model_name='plantstatus',
            name='moisture',
            field=models.ManyToManyField(to='sensor.soilmoisture'),
        ),
        migrations.AddField(
            model_name='plantstatus',
            name='surrounding',
            field=models.ManyToManyField(to='sensor.temphumid'),
        ),
    ]
